iris.features.optional = ENTITY_TRANSLUCENT

screen = INFO <empty> <empty> <empty> [DITHER] [COLOR] [GEOMETRY] [FOG]
screen.columns = 2

screen.DITHER = psx_enable_dither psx_dither_strength psx_pattern_scale psx_color_steps
screen.COLOR = psx_post_contrast psx_light_steps
screen.GEOMETRY = psx_post_scale psx_warp_limit psx_affine_held_items psx_enable_vertex_snap psx_vertex_resolution
screen.FOG = psx_fog_enable psx_fog_distance psx_fog_noise

sliders = psx_dither_strength psx_pattern_scale psx_color_steps psx_post_scale psx_post_contrast psx_light_steps psx_warp_limit psx_vertex_resolution psx_fog_distance psx_fog_noise

psx_enable_dither = 1.0 0.0 1.0 1.0
psx_dither_strength = 2.5 1.0 0.25 4.0
psx_pattern_scale = 2.0 1.0 0.5 4.0
psx_color_steps = 31.0 8.0 1.0 32.0
psx_post_scale = 0.25 0.1 0.01 1.0
psx_post_contrast = 0.2 0.0 0.01 0.3
psx_light_steps = 32.0 8.0 1.0 64.0
psx_warp_limit = 1.0 0.25 0.1 2.0
psx_affine_held_items = 0.0 0.0 1.0 1.0
psx_enable_vertex_snap = 1.0 0.0 1.0 1.0
psx_vertex_resolution = 240.0 120.0 1.0 360.0
psx_fog_enable = 1.0 0.0 1.0 1.0
psx_fog_distance = 64.0 16.0 4.0 128.0
psx_fog_noise = 0.0005 0.0 0.00025 0.002